'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8933
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("MPS.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _1243841517_chart_add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1243841517_chart_add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1243841522_chart_accept() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1243841522_chart_accept", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1SMS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1SMS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _exit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property access() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("access", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Accounting() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Accounting", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Accounting1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Accounting1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property add_file() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add file", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property add_folder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add folder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property add_note() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add note", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property add_package() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add package", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property add_user() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add user", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property add_window() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add window", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property anh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("anh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property back_button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("back button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BanHang_t() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BanHang_t", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BaoCaoNVKinhDoanh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BaoCaoNVKinhDoanh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Barcode_32x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Barcode-32x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Bc_MuaHang() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bc_MuaHang", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bell() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bell", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg_bms3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg-bms3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bms_flag_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bms flag ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property book_green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("book_green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property book_green1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("book_green1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property book_green2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("book_green2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property book_red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("book_red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property book_yellow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("book_yellow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property books() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("books", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property box() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("box", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property box_closed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("box_closed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property box_into() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("box_into", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property box_out() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("box_out", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property box1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("box1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property businessmen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("businessmen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_info() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button-info", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property calculator() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("calculator", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cancl_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cancl_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CapNhapGiaHH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CapNhapGiaHH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CapNhatGiaHang() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CapNhatGiaHang", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cargo3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cargo3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CauTaoThanhPham() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CauTaoThanhPham", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CauTaoTP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CauTaoTP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ChamCong_t() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ChamCong_t", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Chart_Bar_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Chart Bar 2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property check() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("check", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Chon_Tat_Ca() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Chon_Tat_Ca", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ChuyenKho() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ChuyenKho", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CK_DonHang() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CK_DonHang", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Clipboard_Configuration() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Clipboard Configuration", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property connect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("connect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property contract() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("contract", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property COPY() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("COPY", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cube_green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cube_green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cubes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cubes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dangnhap() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dangnhap", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DangNhap_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DangNhap_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Danh_Muc2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Danh_Muc2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Danh_Muc32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Danh_Muc32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property data() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("data", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property database_list132x32_24_bit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("database list132x32 24-bit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DatHangXuat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DatHangXuat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DB_web() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DB web", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property del_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("del_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property delete1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property delete2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property desktop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("desktop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dichvu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dichvu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dichvu3232() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dichvu3232", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Dieu_Chinh_Hien_Thi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dieu_Chinh_Hien_Thi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property disk_blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("disk_blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property disk_blue1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("disk_blue1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property disk_yellow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("disk_yellow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property disk_yellow1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("disk_yellow1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dm_KhoHang() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dm_KhoHang", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dm_KhOHang2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dm_KhOHang2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property document() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property document_add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document_add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property document_down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document_down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property document_lock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document_lock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property document_new() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document_new", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property document_ok() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document_ok", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property document_ok1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document_ok1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property document_out() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document_out", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property document_out1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document_out1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property document_up() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document_up", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property documents() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("documents", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dollar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dollar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DonViTienTe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DonViTienTe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property download_package() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("download package", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ds_BaoGia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ds_BaoGia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ds_ChuyenKho() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ds_ChuyenKho", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ds_DatHangXuat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ds_DatHangXuat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ds_KiemKho() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ds_KiemKho", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ds_NhanVien_t() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ds_NhanVien_t", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ds_PhieuChi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ds_PhieuChi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ds_PhieuChi_t() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ds_PhieuChi_t", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ds_PhieuDatMuaHang() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ds_PhieuDatMuaHang", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ds_PhieuNhapHangTra() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ds_PhieuNhapHangTra", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ds_PhieuNhapMuaHang() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ds_PhieuNhapMuaHang", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ds_PhieuThu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ds_PhieuThu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ds_PhieuXuatHangBan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ds_PhieuXuatHangBan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ds_PhieuXuatTraHang() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ds_PhieuXuatTraHang", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property edit_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit 2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property edit1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property edit2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property edit3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Email() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Email", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Excel2002() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Excel2002", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property exit_child() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exit child", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property exit1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exit1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property export() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("export", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property export1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("export1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property export2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("export2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property filter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("filter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property find() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("find", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property forward_button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forward button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property globe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("globe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property graphics_tablet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("graphics-tablet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property graphics_tablet1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("graphics-tablet1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property group32x32_24_bit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("group32x32 24-bit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Hang_Hoa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hang_Hoa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property HangHoa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HangHoa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property help() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("help", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property help_earth() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("help_earth", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property help2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("help2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Hieu_Chinh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hieu_Chinh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property home() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("home", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property home1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("home1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property home32x32_24_bit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("home32x32 24-bit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property HoTroOnline() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HoTroOnline", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property house() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("house", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property id_cards() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("id_cards", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Image1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Image1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property import1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("import1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property import2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("import2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property import3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("import3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property index_add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("index_add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property index_view() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("index_view", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property information() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("information", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property invoice() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("invoice", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property item232x32_24_bit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("item232x32 24-bit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property item432x32_24_bit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("item432x32 24-bit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property key1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("key1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property KhoHang() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("KhoHang", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property KhoHang_t() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("KhoHang_t", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property KhoiTaoHangTonDK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("KhoiTaoHangTonDK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Kiem_Kho() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Kiem_Kho", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property KiemKho() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("KiemKho", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property label_green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("label-green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property label_red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("label-red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property label_yellow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("label-yellow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Login() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Login", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logo_vsoft_ko_mau() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo-vsoft-ko-mau", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logovsoftl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logovsoftl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Luu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Luu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Luu_Thoat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Luu_Thoat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property material_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("material_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property material_48x48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("material_48x48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property material_651() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("material_651", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property money() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("money", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property money_envelope() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("money_envelope", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property money2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("money2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property moneybag() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("moneybag", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property moneybag_dollar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("moneybag_dollar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property moneybag_euro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("moneybag_euro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MucGia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MucGia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property nav_left_blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nav_left_blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property nav_right_blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nav_right_blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property navigate_beginning() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("navigate_beginning", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property navigate_down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("navigate_down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property navigate_end() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("navigate_end", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property navigate_left() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("navigate_left", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property navigate_right() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("navigate_right", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property new_item232x32_24_bit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("new-item232x32 24-bit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property new_item432x32_24_bit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("new-item432x32 24-bit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property newdatabase() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("newdatabase", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NganhHang() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NganhHang", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Nhan_Vien() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nhan_Vien", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Nhan_Vien32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nhan_Vien32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property nhap() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nhap", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Nhap_Khac() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nhap_Khac", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NhapKhac() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NhapKhac", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Nhom_Hang() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nhom_Hang", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Nhom_Hang1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nhom_Hang1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NhomNguoiDung() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NhomNguoiDung", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property note() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("note", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property note_add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("note_add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property note_edit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("note_edit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property note_new() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("note_new", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ok() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ok", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ok2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ok2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Organization32x32_24_bit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Organization32x32 24-bit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property package() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("package", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property package1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("package1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property percent() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("percent", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PheuXuatKhac() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PheuXuatKhac", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PhieuBaoGia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PhieuBaoGia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PhieuBaoGia01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PhieuBaoGia01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PhieuChiTien() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PhieuChiTien", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PhieuChuyenKho() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PhieuChuyenKho", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PhieuDatHangXuat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PhieuDatHangXuat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PhieuDatNhapHang() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PhieuDatNhapHang", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PhieuNhapHangTra() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PhieuNhapHangTra", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PhieuNhapKhac() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PhieuNhapKhac", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PhieuNhapMua() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PhieuNhapMua", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PhieuNhapMuaHang() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PhieuNhapMuaHang", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PhieuThuTien() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PhieuThuTien", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PhieuXuatChuyenKho() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PhieuXuatChuyenKho", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PhieuXuatHangBan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PhieuXuatHangBan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PhieuXuatHangNhapTra() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PhieuXuatHangNhapTra", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PhieuXuatKhac() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PhieuXuatKhac", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PhieuXuatTraHang() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PhieuXuatTraHang", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pos_about() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pos-about", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pos_title() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pos-title", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property printer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("printer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property product() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("product", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property product2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("product2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PX_HangBan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PX_HangBan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property QuanHuyen_t() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("QuanHuyen_t", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property question_and_answer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("question_and_answer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property QuocGia_t() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("QuocGia_t", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property refresh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("refresh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property refresh1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("refresh1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property reload32x32_24_bit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reload32x32 24-bit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sales() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sales", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sales32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sales32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Save_2__Cancel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Save 2  Cancel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Save_Add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Save Add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property server_client_exchange() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("server_client_exchange", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property server_to_client() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("server_to_client", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property statistics4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("statistics4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property table_selection_all() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("table_selection_all", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property table_sql_check() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("table_sql_check", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property table_sql_delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("table_sql_delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Task_New() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Task New", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Them_Moi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Them_Moi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property thoatct() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("thoatct", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ThongKe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ThongKe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ThongKeHangToan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ThongKeHangToan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Thu_khac() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Thu khac", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property THUCHI() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("THUCHI", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property THUCHI32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("THUCHI32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ThuKhac_t() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ThuKhac_t", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Tim_Kiem() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tim_Kiem", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Tinh_Thanh_t() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tinh_Thanh_t", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Tinh_Thanh1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tinh_Thanh1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TinhLuong() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TinhLuong", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tools() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tools", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property unknown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("unknown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Unknown232x32_24_bit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Unknown232x32 24-bit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to alter VIEW dbo.V_Orders    
        '''AS    
        '''SELECT   v.s_IDFromHQ,  e.s_Name AS EmployeeName, o.s_Name AS ObjectName, c.s_Name AS ContactName,o.s_Object_ID as ObjectID,    
        '''q.s_Order_ID AS QuoteID, p.s_Order_ID AS PurchaseID, t.s_Name AS TermName, v.s_ID,    
        '''v.s_Order_ID, v.s_Char, v.i_ItemID, v.dt_OrderDate, v.s_EmployeeID, v.s_ObjectID,    
        '''v.s_DeliverableAddresss, v.s_PayabbleAddress, v.s_ContactID, v.m_Ordertotal, v.s_Note,    
        '''v.f_VAT, v.m_VAT, v.f_Discount, v.m_OrderTotalDiscount, v.f_Per, v.m_Per, v.i_ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property UpgradeDB() As String
            Get
                Return ResourceManager.GetString("UpgradeDB", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property upload_package() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("upload package", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property upload32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("upload32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property user_headphones() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user_headphones", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property user_headset() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user_headset", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property user1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property user11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property user2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property user3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property User32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("User32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property UserGroup() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UserGroup", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property users1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("users1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property users2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("users2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property users21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("users21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property users22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("users22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property users3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("users3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property users4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("users4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property V_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("V.icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Vidu1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vidu1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property vietnam() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vietnam", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property view() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("view", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Vista__257_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vista (257)32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Vista32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vista32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property VsoftBMS_logo() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("VsoftBMS_logo", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property web_page32x32_24_bit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("web page32x32 24-bit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WWW() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WWW", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Xoa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Xoa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property xoa2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("xoa2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property xuat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("xuat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Xuat_Khac() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Xuat_Khac", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property yes32x32_24_bit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("yes32x32 24-bit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
