'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8922
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property GroupReportOfImport() As String
            Get
                Return CType(Me("GroupReportOfImport"),String)
            End Get
            Set
                Me("GroupReportOfImport") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property GroupObjReportOfImport() As String
            Get
                Return CType(Me("GroupObjReportOfImport"),String)
            End Get
            Set
                Me("GroupObjReportOfImport") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property GroupReportOfOrder() As String
            Get
                Return CType(Me("GroupReportOfOrder"),String)
            End Get
            Set
                Me("GroupReportOfOrder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property GroupObjReportOfOrder() As String
            Get
                Return CType(Me("GroupObjReportOfOrder"),String)
            End Get
            Set
                Me("GroupObjReportOfOrder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property FilterForGrid_Outcome() As Integer
            Get
                Return CType(Me("FilterForGrid_Outcome"),Integer)
            End Get
            Set
                Me("FilterForGrid_Outcome") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property FilterForGrid_Outcome_State() As Integer
            Get
                Return CType(Me("FilterForGrid_Outcome_State"),Integer)
            End Get
            Set
                Me("FilterForGrid_Outcome_State") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property FilterForGrid_ImportReturn() As Integer
            Get
                Return CType(Me("FilterForGrid_ImportReturn"),Integer)
            End Get
            Set
                Me("FilterForGrid_ImportReturn") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ChooseviewImportReturn() As Integer
            Get
                Return CType(Me("ChooseviewImportReturn"),Integer)
            End Get
            Set
                Me("ChooseviewImportReturn") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ChooseviewGroupImportReturn() As String
            Get
                Return CType(Me("ChooseviewGroupImportReturn"),String)
            End Get
            Set
                Me("ChooseviewGroupImportReturn") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property cboGroupObjectImportReturn() As String
            Get
                Return CType(Me("cboGroupObjectImportReturn"),String)
            End Get
            Set
                Me("cboGroupObjectImportReturn") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ChooseviewStoreImportReturn() As String
            Get
                Return CType(Me("ChooseviewStoreImportReturn"),String)
            End Get
            Set
                Me("ChooseviewStoreImportReturn") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ChooseviewPurchaseImport() As String
            Get
                Return CType(Me("ChooseviewPurchaseImport"),String)
            End Get
            Set
                Me("ChooseviewPurchaseImport") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ChooseviewStoreOrderReturn() As String
            Get
                Return CType(Me("ChooseviewStoreOrderReturn"),String)
            End Get
            Set
                Me("ChooseviewStoreOrderReturn") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property cboObjectGroupOrderReturn() As String
            Get
                Return CType(Me("cboObjectGroupOrderReturn"),String)
            End Get
            Set
                Me("cboObjectGroupOrderReturn") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property KeyEnter() As Integer
            Get
                Return CType(Me("KeyEnter"),Integer)
            End Get
            Set
                Me("KeyEnter") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property SelectDefaultObject() As Boolean
            Get
                Return CType(Me("SelectDefaultObject"),Boolean)
            End Get
            Set
                Me("SelectDefaultObject") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property IsMemberGroup() As Boolean
            Get
                Return CType(Me("IsMemberGroup"),Boolean)
            End Get
            Set
                Me("IsMemberGroup") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ArrAddressLan() As String
            Get
                Return CType(Me("ArrAddressLan"),String)
            End Get
            Set
                Me("ArrAddressLan") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ChooseviewImport() As Integer
            Get
                Return CType(Me("ChooseviewImport"),Integer)
            End Get
            Set
                Me("ChooseviewImport") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ChoosePaymentImport() As Integer
            Get
                Return CType(Me("ChoosePaymentImport"),Integer)
            End Get
            Set
                Me("ChoosePaymentImport") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ChooseviewStoreImport() As String
            Get
                Return CType(Me("ChooseviewStoreImport"),String)
            End Get
            Set
                Me("ChooseviewStoreImport") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property cboGroupObjectImport() As String
            Get
                Return CType(Me("cboGroupObjectImport"),String)
            End Get
            Set
                Me("cboGroupObjectImport") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ChooseviewOrder() As Integer
            Get
                Return CType(Me("ChooseviewOrder"),Integer)
            End Get
            Set
                Me("ChooseviewOrder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ChooseviewGroupOrderReturn() As String
            Get
                Return CType(Me("ChooseviewGroupOrderReturn"),String)
            End Get
            Set
                Me("ChooseviewGroupOrderReturn") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property NoUseListProductOrderReturn() As Boolean
            Get
                Return CType(Me("NoUseListProductOrderReturn"),Boolean)
            End Get
            Set
                Me("NoUseListProductOrderReturn") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ChooseviewOrderReturn() As Integer
            Get
                Return CType(Me("ChooseviewOrderReturn"),Integer)
            End Get
            Set
                Me("ChooseviewOrderReturn") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property NoUseListProductImport() As Boolean
            Get
                Return CType(Me("NoUseListProductImport"),Boolean)
            End Get
            Set
                Me("NoUseListProductImport") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ChooseviewGroupImport() As String
            Get
                Return CType(Me("ChooseviewGroupImport"),String)
            End Get
            Set
                Me("ChooseviewGroupImport") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property cboGroupObjectPurchaseImport() As String
            Get
                Return CType(Me("cboGroupObjectPurchaseImport"),String)
            End Get
            Set
                Me("cboGroupObjectPurchaseImport") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property NoUseListProductPurchaseImport() As Boolean
            Get
                Return CType(Me("NoUseListProductPurchaseImport"),Boolean)
            End Get
            Set
                Me("NoUseListProductPurchaseImport") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ServerAddress() As String
            Get
                Return CType(Me("ServerAddress"),String)
            End Get
            Set
                Me("ServerAddress") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property GroupObjReportOfTotal() As String
            Get
                Return CType(Me("GroupObjReportOfTotal"),String)
            End Get
            Set
                Me("GroupObjReportOfTotal") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ChooseviewGroupPurchaseImport() As String
            Get
                Return CType(Me("ChooseviewGroupPurchaseImport"),String)
            End Get
            Set
                Me("ChooseviewGroupPurchaseImport") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property GroupReportOfTotal() As String
            Get
                Return CType(Me("GroupReportOfTotal"),String)
            End Get
            Set
                Me("GroupReportOfTotal") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property FilterForGrid_PurchaseImport() As Integer
            Get
                Return CType(Me("FilterForGrid_PurchaseImport"),Integer)
            End Get
            Set
                Me("FilterForGrid_PurchaseImport") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property FilterForGrid_PurchaseImport_State() As Integer
            Get
                Return CType(Me("FilterForGrid_PurchaseImport_State"),Integer)
            End Get
            Set
                Me("FilterForGrid_PurchaseImport_State") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property NoUseListProductImportReturn() As Boolean
            Get
                Return CType(Me("NoUseListProductImportReturn"),Boolean)
            End Get
            Set
                Me("NoUseListProductImportReturn") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property FilterForGrid_OrderTotal() As Integer
            Get
                Return CType(Me("FilterForGrid_OrderTotal"),Integer)
            End Get
            Set
                Me("FilterForGrid_OrderTotal") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Viewbeforeprint() As Boolean
            Get
                Return CType(Me("Viewbeforeprint"),Boolean)
            End Get
            Set
                Me("Viewbeforeprint") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ReportPrint() As String
            Get
                Return CType(Me("ReportPrint"),String)
            End Get
            Set
                Me("ReportPrint") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ChooseviewGroupOrder() As String
            Get
                Return CType(Me("ChooseviewGroupOrder"),String)
            End Get
            Set
                Me("ChooseviewGroupOrder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ChooseviewPurchaseOrder() As Integer
            Get
                Return CType(Me("ChooseviewPurchaseOrder"),Integer)
            End Get
            Set
                Me("ChooseviewPurchaseOrder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property cboObjectGroupPurchseOrder() As String
            Get
                Return CType(Me("cboObjectGroupPurchseOrder"),String)
            End Get
            Set
                Me("cboObjectGroupPurchseOrder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property NoUseListProductPurchaseOrder() As Boolean
            Get
                Return CType(Me("NoUseListProductPurchaseOrder"),Boolean)
            End Get
            Set
                Me("NoUseListProductPurchaseOrder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ChooseviewGroupPurchaseOrder() As String
            Get
                Return CType(Me("ChooseviewGroupPurchaseOrder"),String)
            End Get
            Set
                Me("ChooseviewGroupPurchaseOrder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property FilePath() As String
            Get
                Return CType(Me("FilePath"),String)
            End Get
            Set
                Me("FilePath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property NumBarcode() As String
            Get
                Return CType(Me("NumBarcode"),String)
            End Get
            Set
                Me("NumBarcode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property NumBarcodeRow() As String
            Get
                Return CType(Me("NumBarcodeRow"),String)
            End Get
            Set
                Me("NumBarcodeRow") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property FilterForGrid_Import() As Integer
            Get
                Return CType(Me("FilterForGrid_Import"),Integer)
            End Get
            Set
                Me("FilterForGrid_Import") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property FilterForGrid_Income() As Integer
            Get
                Return CType(Me("FilterForGrid_Income"),Integer)
            End Get
            Set
                Me("FilterForGrid_Income") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property FilterForGrid_Income_State() As Integer
            Get
                Return CType(Me("FilterForGrid_Income_State"),Integer)
            End Get
            Set
                Me("FilterForGrid_Income_State") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property FilterForGrid_PurchaseOrder_State() As Integer
            Get
                Return CType(Me("FilterForGrid_PurchaseOrder_State"),Integer)
            End Get
            Set
                Me("FilterForGrid_PurchaseOrder_State") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property FilterForGrid_PurchaseOrder() As Integer
            Get
                Return CType(Me("FilterForGrid_PurchaseOrder"),Integer)
            End Get
            Set
                Me("FilterForGrid_PurchaseOrder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ChooseviewQuote() As Integer
            Get
                Return CType(Me("ChooseviewQuote"),Integer)
            End Get
            Set
                Me("ChooseviewQuote") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property cboObjectGroupQuote() As String
            Get
                Return CType(Me("cboObjectGroupQuote"),String)
            End Get
            Set
                Me("cboObjectGroupQuote") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ChooseviewGroupQuote() As String
            Get
                Return CType(Me("ChooseviewGroupQuote"),String)
            End Get
            Set
                Me("ChooseviewGroupQuote") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property FilterForGrid_OrderReturn() As Integer
            Get
                Return CType(Me("FilterForGrid_OrderReturn"),Integer)
            End Get
            Set
                Me("FilterForGrid_OrderReturn") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property GroupReportOfStore() As String
            Get
                Return CType(Me("GroupReportOfStore"),String)
            End Get
            Set
                Me("GroupReportOfStore") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ChoosePaymentOrder() As Integer
            Get
                Return CType(Me("ChoosePaymentOrder"),Integer)
            End Get
            Set
                Me("ChoosePaymentOrder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ViewImage() As Boolean
            Get
                Return CType(Me("ViewImage"),Boolean)
            End Get
            Set
                Me("ViewImage") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property NoUseListProduct() As Boolean
            Get
                Return CType(Me("NoUseListProduct"),Boolean)
            End Get
            Set
                Me("NoUseListProduct") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property CheckOrderTM() As Boolean
            Get
                Return CType(Me("CheckOrderTM"),Boolean)
            End Get
            Set
                Me("CheckOrderTM") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property CheckOrderCK() As Boolean
            Get
                Return CType(Me("CheckOrderCK"),Boolean)
            End Get
            Set
                Me("CheckOrderCK") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property CurrentLayout() As Integer
            Get
                Return CType(Me("CurrentLayout"),Integer)
            End Get
            Set
                Me("CurrentLayout") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ChooseviewStoreOrder() As String
            Get
                Return CType(Me("ChooseviewStoreOrder"),String)
            End Get
            Set
                Me("ChooseviewStoreOrder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property GroupObject() As String
            Get
                Return CType(Me("GroupObject"),String)
            End Get
            Set
                Me("GroupObject") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property FilterForGrid_Quote() As Integer
            Get
                Return CType(Me("FilterForGrid_Quote"),Integer)
            End Get
            Set
                Me("FilterForGrid_Quote") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property FilterForGrid_Quote_State() As Integer
            Get
                Return CType(Me("FilterForGrid_Quote_State"),Integer)
            End Get
            Set
                Me("FilterForGrid_Quote_State") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ChooseviewStoreCheck() As String
            Get
                Return CType(Me("ChooseviewStoreCheck"),String)
            End Get
            Set
                Me("ChooseviewStoreCheck") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property NoUseListProductQuote() As Boolean
            Get
                Return CType(Me("NoUseListProductQuote"),Boolean)
            End Get
            Set
                Me("NoUseListProductQuote") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property FilterForGrid_Order() As Integer
            Get
                Return CType(Me("FilterForGrid_Order"),Integer)
            End Get
            Set
                Me("FilterForGrid_Order") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ChooseviewGroupTrans() As String
            Get
                Return CType(Me("ChooseviewGroupTrans"),String)
            End Get
            Set
                Me("ChooseviewGroupTrans") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property NoUseListProductTrabsfer() As Boolean
            Get
                Return CType(Me("NoUseListProductTrabsfer"),Boolean)
            End Get
            Set
                Me("NoUseListProductTrabsfer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ChooseviewTrans() As Integer
            Get
                Return CType(Me("ChooseviewTrans"),Integer)
            End Get
            Set
                Me("ChooseviewTrans") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property FilterForGrid_Transfer() As Integer
            Get
                Return CType(Me("FilterForGrid_Transfer"),Integer)
            End Get
            Set
                Me("FilterForGrid_Transfer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property MaxColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("MaxColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("MaxColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property MinColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("MinColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("MinColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property FilterForGrid_TransCurr() As Integer
            Get
                Return CType(Me("FilterForGrid_TransCurr"),Integer)
            End Get
            Set
                Me("FilterForGrid_TransCurr") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property FilterForGrid_OrderOther() As Integer
            Get
                Return CType(Me("FilterForGrid_OrderOther"),Integer)
            End Get
            Set
                Me("FilterForGrid_OrderOther") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ChooseviewStoreOrderOther() As String
            Get
                Return CType(Me("ChooseviewStoreOrderOther"),String)
            End Get
            Set
                Me("ChooseviewStoreOrderOther") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property NoUseListProductOtherOrder() As Boolean
            Get
                Return CType(Me("NoUseListProductOtherOrder"),Boolean)
            End Get
            Set
                Me("NoUseListProductOtherOrder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property cboObjectGroupOtherOrder() As String
            Get
                Return CType(Me("cboObjectGroupOtherOrder"),String)
            End Get
            Set
                Me("cboObjectGroupOtherOrder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ChooseviewGroupOrderOther() As String
            Get
                Return CType(Me("ChooseviewGroupOrderOther"),String)
            End Get
            Set
                Me("ChooseviewGroupOrderOther") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property cboObjectGroupOtherImport() As String
            Get
                Return CType(Me("cboObjectGroupOtherImport"),String)
            End Get
            Set
                Me("cboObjectGroupOtherImport") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property FilterForGrid_ImportOther() As Integer
            Get
                Return CType(Me("FilterForGrid_ImportOther"),Integer)
            End Get
            Set
                Me("FilterForGrid_ImportOther") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ChooseviewOrderOther() As Integer
            Get
                Return CType(Me("ChooseviewOrderOther"),Integer)
            End Get
            Set
                Me("ChooseviewOrderOther") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ChooseviewStoreImportOther() As String
            Get
                Return CType(Me("ChooseviewStoreImportOther"),String)
            End Get
            Set
                Me("ChooseviewStoreImportOther") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PaymentImportOther() As String
            Get
                Return CType(Me("PaymentImportOther"),String)
            End Get
            Set
                Me("PaymentImportOther") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property NoUseListProductOtherImport() As Boolean
            Get
                Return CType(Me("NoUseListProductOtherImport"),Boolean)
            End Get
            Set
                Me("NoUseListProductOtherImport") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ChooseviewImportOther() As Integer
            Get
                Return CType(Me("ChooseviewImportOther"),Integer)
            End Get
            Set
                Me("ChooseviewImportOther") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ChooseviewGroupImportOther() As String
            Get
                Return CType(Me("ChooseviewGroupImportOther"),String)
            End Get
            Set
                Me("ChooseviewGroupImportOther") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Install() As Integer
            Get
                Return CType(Me("Install"),Integer)
            End Get
            Set
                Me("Install") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property UnInstall() As Integer
            Get
                Return CType(Me("UnInstall"),Integer)
            End Get
            Set
                Me("UnInstall") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property cboGroupProductInstock() As String
            Get
                Return CType(Me("cboGroupProductInstock"),String)
            End Get
            Set
                Me("cboGroupProductInstock") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property cboStockProductInstock() As String
            Get
                Return CType(Me("cboStockProductInstock"),String)
            End Get
            Set
                Me("cboStockProductInstock") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property GroupObjReportOfEmployeeSale() As String
            Get
                Return CType(Me("GroupObjReportOfEmployeeSale"),String)
            End Get
            Set
                Me("GroupObjReportOfEmployeeSale") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property cboStoreBeginProduct() As String
            Get
                Return CType(Me("cboStoreBeginProduct"),String)
            End Get
            Set
                Me("cboStoreBeginProduct") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property cboGroupBeginProduct() As String
            Get
                Return CType(Me("cboGroupBeginProduct"),String)
            End Get
            Set
                Me("cboGroupBeginProduct") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property LengUpdateDB() As Integer
            Get
                Return CType(Me("LengUpdateDB"),Integer)
            End Get
            Set
                Me("LengUpdateDB") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property s_ViewProductStock() As Boolean
            Get
                Return CType(Me("s_ViewProductStock"),Boolean)
            End Get
            Set
                Me("s_ViewProductStock") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property FilterPath() As String
            Get
                Return CType(Me("FilterPath"),String)
            End Get
            Set
                Me("FilterPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property isRem() As Boolean
            Get
                Return CType(Me("isRem"),Boolean)
            End Get
            Set
                Me("isRem") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property UID() As String
            Get
                Return CType(Me("UID"),String)
            End Get
            Set
                Me("UID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PWD() As String
            Get
                Return CType(Me("PWD"),String)
            End Get
            Set
                Me("PWD") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.MPS.My.MySettings
            Get
                Return Global.MPS.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
